
export const MAKE_QUOTATION="MAKE_QUOTATION";
export const STORE_QUOTATION="STORE_QUOTATION";
export const DELETE_QUOTATION="DELETE_QUOTATION";
export const VIEW_QUOTATION="VIEW_QUOTATION";
export const GET_QUOTATIONS="ALL_QUOTATION";
export const SET_QUOTATION="SET_QUOTATION";
export const CLEAR_QUOTATION="CLEAR_QUOTATION";

export const GET_CURRENCY="GET_CURRENCY";